question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit "
             "an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral."
        , "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {
        "text": "The HTML5 standard was published in 2014.", "answer": "True"},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "text": "The first computer bug was formed by faulty wires.", "answer": "False",
     "inanswers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "text": "FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;",
     "answer": "False", "inanswers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "text": "&quot;Windows NT&quot; is a monolithic kernel.", "answer": "False",
     "inanswers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "text": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
     "answer": "True", "inanswers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "text": "RAM stands for Random Access Memory.", "answer": "True", "inanswers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
     "text": "AMD created the first consumer 64-bit processor.", "answer": "True",
     "inanswers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
     "text": "DHCP stands for Dynamic Host Configuration Port.",
     "answer": "False", "inanswers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "text": "Time on Computers is measured via the EPOX System.", "answer": "False",
     "inanswers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
     "text": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
     "answer": "True", "inanswers": ["False"], }
]
